name = "vexryl-platform"
compatibility_date = "2024-09-01"

# Cloudflare Pages output directory (required for wrangler Pages integration)
pages_build_output_dir = "apps/web/dist"

[env.production]
name = "vexryl-platform"

# This is for Pages deployment - build configuration
# Build command: npm run build
# Build output directory: apps/web/dist
