name = "vexryl-platform"
compatibility_date = "2024-09-01"

[env.production]
name = "vexryl-platform"

# This is for Pages deployment - build configuration
# Build command: npm run build
# Build output directory: apps/web/dist
