## Optional Cloudflare Worker config (NOT required for Pages)
# name = "vexryl-api"
# main = "worker.js"
# compatibility_date = "2024-09-01"

# Environment variables should be added via `wrangler.toml` only if deploying this worker.
# Remove any hard-coded secrets. Use `wrangler secret put` for sensitive values.
#[vars]
# SUPABASE_URL = "https://your-project.supabase.co"
# SUPABASE_ANON_KEY = "your-anon-key"

#[env.development]
# name = "vexryl-api-dev"

#[env.production]
# name = "vexryl-api-prod"

# Secrets (set with: wrangler secret put SUPABASE_SERVICE_ROLE_KEY)
# SUPABASE_SERVICE_ROLE_KEY
# GITHUB_TOKEN

#[[kv_namespaces]]
# binding = "CACHE"
# id = "your_kv_namespace_id"
# preview_id = "your_kv_preview_id"
