name = "vexryl-api"
main = "src/index.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "vexryl-api"

[env.development]
name = "vexryl-api-dev"

# Environment variables - set via Cloudflare dashboard
[vars]
ENVIRONMENT = "production"
API_VERSION = "v1"

# Remove any hard-coded secrets. Use `wrangler secret put` for sensitive values.
# Set these secrets via: wrangler secret put SECRET_NAME
# SUPABASE_URL
# SUPABASE_ANON_KEY  
# SUPABASE_SERVICE_ROLE_KEY
# GITHUB_TOKEN
# DISCORD_CLIENT_SECRET

#[[kv_namespaces]]
# binding = "CACHE"
# id = "your_kv_namespace_id"
# preview_id = "your_kv_preview_id"
